In [2]:
import os
import sys
import gc 
import glob 

import pandas as pd
pd.set_option('display.max_columns', 500)
import numpy as np

# Concat

In [ ]:
df = pd.read_csv('N10E106_1_1_100m_2022-11-01.csv')
df.dtypesilqrstvwyz12457890

Timestamp               object
lon                    float64
lat                    float64
CropType                object
Country                 object
RVI_mean               float64
PM25_mean              float64
PM25_max               float64
NO2_mean               float64
NO2_max                float64
O3_mean                float64
O3_max                 float64
SO2_mean               float64
SO2_max                float64
Temperature_mean       float64
Temperature_max        float64
Wind_speed_mean        float64
Wind_direction_mean    float64
Wind_speed_max         float64
Rel_humidity_mean      float64
Precipitation_sum      float64
Luminosity             float64
elevation                int64
dtype: object

In [4]:
df.memory_usage()

Index                     132
Timestamp              394416
lon                    394416
lat                    394416
CropType               394416
Country                394416
RVI_mean               394416
PM25_mean              394416
PM25_max               394416
NO2_mean               394416
NO2_max                394416
O3_mean                394416
O3_max                 394416
SO2_mean               394416
SO2_max                394416
Temperature_mean       394416
Temperature_max        394416
Wind_speed_mean        394416
Wind_direction_mean    394416
Wind_speed_max         394416
Rel_humidity_mean      394416
Precipitation_sum      394416
Luminosity             394416
elevation              394416
dtype: int64

In [5]:
df1 = pd.read_csv('N10E106_1_1_100m_2022-11-01.csv',
                  dtype={'RVI_mean': np.float16,
                         'PM25_mean': np.float16,
                         'PM25_max': np.float16,
                         'NO2_mean': np.float16,
                         'NO2_max': np.float16,
                         'O3_mean': np.float16,
                         'O3_max': np.float16,
                         'SO2_mean': np.float16,
                         'SO2_max': np.float16,
                         'Temperature_mean': np.float16,
                         'Temperature_max': np.float16,
                         'Wind_speed_mean': np.float16,
                         'Wind_speed_max': np.float16,
                         'Wind_direction_mean': np.float16,
                         'Rel_humidity_mean': np.float16,
                         'Precipitation_sum': np.float16,
                         'Luminosity': np.float16,
                         'elevation': np.int16})
df1.dtypes

Timestamp               object
lon                    float64
lat                    float64
CropType                object
Country                 object
RVI_mean               float16
PM25_mean              float16
PM25_max               float16
NO2_mean               float16
NO2_max                float16
O3_mean                float16
O3_max                 float16
SO2_mean               float16
SO2_max                float16
Temperature_mean       float16
Temperature_max        float16
Wind_speed_mean        float16
Wind_direction_mean    float16
Wind_speed_max         float16
Rel_humidity_mean      float16
Precipitation_sum      float16
Luminosity             float16
elevation                int16
dtype: object

In [6]:
df1.memory_usage()

Index                     132
Timestamp              394416
lon                    394416
lat                    394416
CropType               394416
Country                394416
RVI_mean                98604
PM25_mean               98604
PM25_max                98604
NO2_mean                98604
NO2_max                 98604
O3_mean                 98604
O3_max                  98604
SO2_mean                98604
SO2_max                 98604
Temperature_mean        98604
Temperature_max         98604
Wind_speed_mean         98604
Wind_direction_mean     98604
Wind_speed_max          98604
Rel_humidity_mean       98604
Precipitation_sum       98604
Luminosity              98604
elevation               98604
dtype: int64

In [7]:
df.head()

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,NO2_mean,NO2_max,...,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation
0,2022-11-01,106.573880,10.000495,Rice,VN,0.450371,15.453761,50.073555,0.000051,0.00007,...,0.000918,26.542974,27.599003,2.137379,-1.544906,3.316996,0.865365,0.245321,0.900000,0
1,2022-11-01,106.574778,10.000495,Rice,VN,0.422950,15.453761,50.073555,0.000051,0.00007,...,0.000918,26.542974,27.599003,2.137379,-1.544906,3.316996,0.865365,0.245321,0.900000,-2
2,2022-11-01,106.575676,10.000495,Rice,VN,0.476376,15.453761,50.073555,0.000051,0.00007,...,0.000918,26.542974,27.599003,2.137379,-1.544906,3.316996,0.865365,0.245321,0.900000,-1
3,2022-11-01,106.576574,10.000495,Rice,VN,0.435539,15.453761,50.073555,0.000051,0.00007,...,0.000918,26.542974,27.599003,2.137379,-1.544906,3.316996,0.865365,0.245321,0.900000,1
4,2022-11-01,106.577473,10.000495,Rice,VN,0.418693,15.453761,50.073555,0.000051,0.00007,...,0.000918,26.542974,27.599003,2.137379,-1.544906,3.316996,0.865365,0.245321,1.366667,-2

In [8]:
df1.head()

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,NO2_mean,NO2_max,...,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation
0,2022-11-01,106.573880,10.000495,Rice,VN,0.450439,15.453125,50.0625,0.000051,0.00007,...,0.000918,26.546875,27.59375,2.136719,-1.544922,3.316406,0.865234,0.245361,0.899902,0
1,2022-11-01,106.574778,10.000495,Rice,VN,0.422852,15.453125,50.0625,0.000051,0.00007,...,0.000918,26.546875,27.59375,2.136719,-1.544922,3.316406,0.865234,0.245361,0.899902,-2
2,2022-11-01,106.575676,10.000495,Rice,VN,0.476318,15.453125,50.0625,0.000051,0.00007,...,0.000918,26.546875,27.59375,2.136719,-1.544922,3.316406,0.865234,0.245361,0.899902,-1
3,2022-11-01,106.576574,10.000495,Rice,VN,0.435547,15.453125,50.0625,0.000051,0.00007,...,0.000918,26.546875,27.59375,2.136719,-1.544922,3.316406,0.865234,0.245361,0.899902,1
4,2022-11-01,106.577473,10.000495,Rice,VN,0.418701,15.453125,50.0625,0.000051,0.00007,...,0.000918,26.546875,27.59375,2.136719,-1.544922,3.316406,0.865234,0.245361,1.366211,-2

In [10]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'outputs_north/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-08-01.csv']

In [18]:
set_paths = set([p[40:50] for p in paths])
set_paths

{'18E105_0_0',
 '18E105_0_1',
 '18E105_1_1',
 '18E106_1_0',
 '19E105_0_0',
 '19E105_0_1',
 '19E105_1_0',
 '19E105_1_1',
 '20E105_0_1',
 '20E105_1_1',
 '20E106_0_0',
 '20E106_0_1',
 '20E106_1_0',
 '20E106_1_1',
 '21E105_0_0',
 '21E105_0_1',
 '21E105_1_0',
 '21E105_1_1',
 '21E106_0_0',
 '21E106_0_1',
 '21E106_1_0',
 '21E106_1_1',
 '21E107_0_1',
 '21E107_1_0',
 '21E107_1_1'}

In [3]:
schema = {'RVI_mean': np.float16,
          'PM25_mean': np.float16,
          'PM25_max': np.float16,
          'NO2_mean': np.float32,
                         'NO2_max': np.float32,
                         'O3_mean': np.float32,
                         'O3_max': np.float32,
                         'SO2_mean': np.float32,
                         'SO2_max': np.float32,
                         'Temperature_mean': np.float16,
                         'Temperature_max': np.float16,
                         'Wind_speed_mean': np.float16,
                         'Wind_speed_max': np.float16,
                         'Wind_direction_mean': np.float16,
                         'Rel_humidity_mean': np.float16,
                         'Precipitation_sum': np.float16,
                         'Luminosity': np.float16,
                         'elevation': np.int8}

In [5]:
list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N09E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/outputs\N10E104_1_1_100m_2018-07-01.csv

In [6]:
full

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,NO2_mean,NO2_max,...,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation
0,2018-01-01,104.865284,9.000670,Rice,VN,0.531738,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.609375,1.906250,-1.392578,1.122070,0.824219,0.093323,0.000000,5
1,2018-01-01,104.903013,9.000670,Rice,VN,0.470459,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.609375,1.906250,-1.392578,1.122070,0.824219,0.093323,0.000000,4
2,2018-01-01,104.951522,9.000670,Rice,VN,0.320068,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,4
3,2018-01-01,104.953319,9.000670,Rice,VN,0.241333,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,5
4,2018-01-01,104.954217,9.000670,Rice,VN,0.228394,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95505785,2022-12-01,106.793967,11.998348,Rice,VN,0.426025,6.839844,22.015625,0.000050,0.000082,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.799805,110
95505786,2022-12-01,106.780492,11.999246,Rice,VN,0.484131,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.599609,99
95505787,2022-12-01,106.783187,11.999246,Rice,VN,0.479492,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.299805,100
95505788,2022-12-01,106.784085,11.999246,Rice,VN,0.472412,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.299805,103
95505789,2022-12-01,106.790374,11.999246,Rice,VN,0.409912,6.839844,22.015625,0.000050,0.000082,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.799805,107

In [9]:
full.drop_duplicates(subset=['Timestamp', 'lat', 'lon'])

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,NO2_mean,NO2_max,...,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation
0,2018-01-01,104.865284,9.000670,Rice,VN,0.531738,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.609375,1.906250,-1.392578,1.122070,0.824219,0.093323,0.000000,5
1,2018-01-01,104.903013,9.000670,Rice,VN,0.470459,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.609375,1.906250,-1.392578,1.122070,0.824219,0.093323,0.000000,4
2,2018-01-01,104.951522,9.000670,Rice,VN,0.320068,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,4
3,2018-01-01,104.953319,9.000670,Rice,VN,0.241333,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,5
4,2018-01-01,104.954217,9.000670,Rice,VN,0.228394,16.953125,52.281250,NaN,NaN,...,NaN,25.84375,26.578125,1.975586,-1.393555,0.922852,0.823242,0.086304,0.000000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95505785,2022-12-01,106.793967,11.998348,Rice,VN,0.426025,6.839844,22.015625,0.000050,0.000082,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.799805,110
95505786,2022-12-01,106.780492,11.999246,Rice,VN,0.484131,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.599609,99
95505787,2022-12-01,106.783187,11.999246,Rice,VN,0.479492,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.299805,100
95505788,2022-12-01,106.784085,11.999246,Rice,VN,0.472412,6.839844,22.015625,0.000049,0.000080,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.299805,103
95505789,2022-12-01,106.790374,11.999246,Rice,VN,0.409912,6.839844,22.015625,0.000050,0.000082,...,0.000376,25.56250,27.718750,2.148438,-0.788086,1.109375,0.619629,0.004128,1.799805,107

In [7]:
full.to_csv('VN_SOUTH.csv', index=False, mode='w')

In [7]:
schema = {'lat': str,
          'lon': str,
          'RVI_mean': np.float16,
          'PM25_mean': np.float16,
          'PM25_max': np.float16,
          'NO2_mean': np.float16,
          'NO2_max': np.float16,
          'O3_mean': np.float16,
          'O3_max': np.float16,
          'SO2_mean': np.float16,
          'SO2_max': np.float16,
          'Temperature_mean': np.float16,
          'Temperature_max': np.float16,
          'Wind_speed_mean': np.float16,
          'Wind_speed_max': np.float16,
          'Wind_direction_mean': np.float16,
          'Rel_humidity_mean': np.float16,
          'Precipitation_sum': np.float16,
          'Luminosity': np.float16,
           'elevation': np.int8}

full = pd.read_csv('VN_SOUTH.csv', dtype=schema)
full['pixel_id'] = full['lon'] + '_' + full['lat']

In [8]:
full['pixel_id'].nunique()

1601166

In [10]:
len(full)

76600645

In [9]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'FIRMS_VNM/*.csv'))
paths.sort()
paths = paths[:]
paths

['G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2016-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2017-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2019-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2020-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2021-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/FIRMS_VNM\\VNM_FIRMS_2022-12-01.csv']

In [10]:
list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2016-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/FIRMS_VNM\VNM_FIRMS_2022-12-01.csv

In [11]:
full

     Timestamp    Mean_T21     Max_T21
0   2016-12-01  318.361525  348.000000
1   2017-01-01  318.296662  348.799988
2   2017-02-01  320.004819  389.399994
3   2017-03-01  321.242242  401.399994
4   2017-04-01  323.043029  434.700012
..         ...         ...         ...
68  2022-08-01  317.740622  375.260010
69  2022-09-01  318.101977  368.049988
70  2022-10-01  315.377749  361.010010
71  2022-11-01  313.946710  353.290009
72  2022-12-01  309.927937  380.480011

[73 rows x 3 columns]

In [12]:
full.to_csv('FIRMS_VNM.csv', index=False)

In [3]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'tropo_south/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_south\\N09E104_1_1_100m_2019-08-01.csv']

In [5]:
df = pd.read_csv(paths[0])
df

         Timestamp         lon       lat  NO2_mean  NO2_max  O3_mean  O3_max
0       2018-01-01  104.500568  9.000670       NaN      NaN      NaN     NaN
1       2018-01-01  104.501466  9.000670       NaN      NaN      NaN     NaN
2       2018-01-01  104.502364  9.000670       NaN      NaN      NaN     NaN
3       2018-01-01  104.503263  9.000670       NaN      NaN      NaN     NaN
4       2018-01-01  104.504161  9.000670       NaN      NaN      NaN     NaN
...            ...         ...       ...       ...      ...      ...     ...
309131  2018-01-01  104.995540  9.499235       NaN      NaN      NaN     NaN
309132  2018-01-01  104.996438  9.499235       NaN      NaN      NaN     NaN
309133  2018-01-01  104.997336  9.499235       NaN      NaN      NaN     NaN
309134  2018-01-01  104.998235  9.499235       NaN      NaN      NaN     NaN
309135  2018-01-01  104.999133  9.499235       NaN      NaN      NaN     NaN

[309136 rows x 7 columns]

In [6]:
schema = {'lat': str,
          'lon': str,
          'NO2_mean': np.float32,
          'NO2_max': np.float32,
          'O3_mean': np.float32,
          'O3_max': np.float32,
          'SO2_mean': np.float32,
          'SO2_max': np.float32,}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E104_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_south\N09E105_1_1_100m_2022-01-01.csv

In [7]:
full.to_csv('tropo_SOUTH.csv', index=False)

In [8]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'tropo_north/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/tropo_north\\N18E105_0_0_100m_2019-08-01.csv']

In [9]:
schema = {'lat': str,
          'lon': str,
          'NO2_mean': np.float32,
          'NO2_max': np.float32,
          'O3_mean': np.float32,
          'O3_max': np.float32,
          'SO2_mean': np.float32,
          'SO2_max': np.float32,}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv('tropo_NORTH.csv', index=False)

G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N18E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/tropo_north\N19E105_0_0_100m_2022-01-01.csv

In [9]:
schema = {'RVI_mean': np.float16,
          'PM25_mean': np.float16,
          'PM25_max': np.float16,
          'NO2_mean': np.float32,
          'NO2_max': np.float32,
          'O3_mean': np.float32,
          'O3_max': np.float32,
          'SO2_mean': np.float32,
          'SO2_max': np.float32,
          'Temperature_mean': np.float16,
          'Temperature_max': np.float16,
          'Wind_speed_mean': np.float16,
          'Wind_speed_max': np.float16,
          'Wind_direction_mean': np.float16,
          'Rel_humidity_mean': np.float16,
          'Precipitation_sum': np.float16,
          'Luminosity': np.float16,
          'elevation': np.int8}

schema_air = {
          'NO2_mean': np.float32,
          'NO2_max': np.float32,
          'O3_mean': np.float32,
          'O3_max': np.float32,
          'SO2_mean': np.float32,
          'SO2_max': np.float32,}


# full = pd.read_csv('VN_NORTH.csv', dtype=schema)

In [10]:
tropo_s = pd.read_csv('tropo_NORTH.csv', dtype=schema_air)

In [12]:
full = full.drop(['NO2_mean', 'NO2_max', 'O3_mean', 'O3_max'], axis=1)
full = pd.merge(full, tropo_s, on=['Timestamp', 'lat', 'lon'], how='left')

In [13]:
full.head()

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,SO2_mean,SO2_max,...,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation,NO2_mean,NO2_max,O3_mean,O3_max
0,2018-01-01,105.330611,18.500354,Rice,VN,0.541992,37.90625,81.1875,NaN,NaN,...,-0.535645,1.207031,0.86377,0.072144,0.0,16,NaN,NaN,NaN,NaN
1,2018-01-01,105.332408,18.500354,Rice,VN,0.052032,37.90625,81.1875,NaN,NaN,...,-0.535645,1.207031,0.86377,0.072144,0.0,24,NaN,NaN,NaN,NaN
2,2018-01-01,105.342289,18.500354,Rice,VN,0.513184,37.90625,81.1875,NaN,NaN,...,-0.535645,1.207031,0.86377,0.072144,0.0,33,NaN,NaN,NaN,NaN
3,2018-01-01,105.344086,18.500354,Rice,VN,0.464600,37.90625,81.1875,NaN,NaN,...,-0.535645,1.207031,0.86377,0.072144,0.0,22,NaN,NaN,NaN,NaN
4,2018-01-01,105.344984,18.500354,Rice,VN,0.459717,37.90625,81.1875,NaN,NaN,...,-0.535645,1.207031,0.86377,0.072144,0.0,17,NaN,NaN,NaN,NaN

In [15]:
len(full)

62105881

In [19]:
full[~full['NO2_mean'].isnull()]

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,SO2_mean,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation,NO2_mean,NO2_max,O3_mean,O3_max
196476,2018-06-01,105.330611,18.500354,Rice,VN,0.559570,10.773438,58.1875,NaN,NaN,27.593750,29.21875,2.013672,0.840332,4.382812,0.763184,0.091980,0.000000,16,0.000018,0.000018,0.011144,0.013995
196480,2018-06-01,105.344984,18.500354,Rice,VN,0.501953,10.773438,58.1875,NaN,NaN,27.593750,29.21875,2.013672,0.840332,4.382812,0.763184,0.091980,0.000000,17,0.000017,0.000017,0.011144,0.013995
196481,2018-06-01,105.366544,18.500354,Rice,VN,0.544922,10.773438,58.1875,NaN,NaN,28.546875,30.00000,1.836914,0.898926,4.472656,0.740234,0.074219,0.000000,16,0.000017,0.000017,0.011144,0.013995
196482,2018-06-01,105.393493,18.500354,Rice,VN,0.497559,10.773438,58.1875,NaN,NaN,28.546875,30.00000,1.836914,0.898926,4.472656,0.740234,0.074219,0.500000,13,0.000016,0.000016,0.011144,0.013995
196483,2018-06-01,105.394392,18.500354,Rice,VN,0.423584,10.773438,58.1875,NaN,NaN,28.546875,30.00000,1.836914,0.898926,4.472656,0.740234,0.074219,0.600098,13,0.000016,0.000016,0.011144,0.013995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13052386,2022-12-01,105.652208,19.498382,Rice,VN,0.414795,35.531250,70.5000,0.000148,0.000809,16.578125,19.09375,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000070,0.000151,0.016660,0.022772
13052387,2022-12-01,105.653106,19.498382,Rice,VN,0.442383,35.531250,70.5000,0.000148,0.000809,16.578125,19.09375,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,13,0.000070,0.000151,0.016660,0.022772
13052388,2022-12-01,105.654005,19.498382,Rice,VN,0.477051,35.531250,70.5000,0.000148,0.000809,16.578125,19.09375,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000070,0.000151,0.016660,0.022772
13052391,2022-12-01,105.748328,19.498382,Rice,VN,0.440186,35.531250,70.5000,0.000158,0.000649,16.578125,19.09375,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,16,0.000088,0.000172,0.016660,0.022772
13052392,2022-12-01,105.749226,19.498382,Rice,VN,0.450684,35.531250,70.5000,0.000158,0.000649,16.578125,19.09375,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000088,0.000172,0.016660,0.022772

In [20]:
full[~full['O3_mean'].isnull()]

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,SO2_mean,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation,NO2_mean,NO2_max,O3_mean,O3_max
157188,2018-05-01,105.330611,18.500354,Rice,VN,0.600586,17.296875,103.625,NaN,NaN,27.390625,28.671875,1.266602,0.662598,2.988281,0.793457,0.119080,0.000000,16,NaN,NaN,0.014568,0.018231
157192,2018-05-01,105.344984,18.500354,Rice,VN,0.515625,17.296875,103.625,NaN,NaN,27.390625,28.671875,1.266602,0.662598,2.988281,0.793457,0.119080,0.000000,17,NaN,NaN,0.014568,0.018231
157193,2018-05-01,105.366544,18.500354,Rice,VN,0.560059,17.296875,103.625,NaN,NaN,28.015625,29.437500,1.087891,0.649902,2.750000,0.791016,0.136841,0.000000,16,NaN,NaN,0.014568,0.018231
157194,2018-05-01,105.393493,18.500354,Rice,VN,0.656738,17.296875,103.625,NaN,NaN,28.015625,29.437500,1.087891,0.649902,2.750000,0.791016,0.136841,0.799805,13,NaN,NaN,0.014568,0.018231
157195,2018-05-01,105.394392,18.500354,Rice,VN,0.619629,17.296875,103.625,NaN,NaN,28.015625,29.437500,1.087891,0.649902,2.750000,0.791016,0.136841,0.500000,13,NaN,NaN,0.014568,0.018231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13052386,2022-12-01,105.652208,19.498382,Rice,VN,0.414795,35.531250,70.500,0.000148,0.000809,16.578125,19.093750,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000070,0.000151,0.016660,0.022772
13052387,2022-12-01,105.653106,19.498382,Rice,VN,0.442383,35.531250,70.500,0.000148,0.000809,16.578125,19.093750,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,13,0.000070,0.000151,0.016660,0.022772
13052388,2022-12-01,105.654005,19.498382,Rice,VN,0.477051,35.531250,70.500,0.000148,0.000809,16.578125,19.093750,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000070,0.000151,0.016660,0.022772
13052391,2022-12-01,105.748328,19.498382,Rice,VN,0.440186,35.531250,70.500,0.000158,0.000649,16.578125,19.093750,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,16,0.000088,0.000172,0.016660,0.022772
13052392,2022-12-01,105.749226,19.498382,Rice,VN,0.450684,35.531250,70.500,0.000158,0.000649,16.578125,19.093750,2.607422,-0.037292,0.820801,0.718750,0.017776,0.000000,14,0.000088,0.000172,0.016660,0.022772

In [21]:
full[~full['SO2_mean'].isnull()]

,Timestamp,lon,lat,CropType,Country,RVI_mean,PM25_mean,PM25_max,SO2_mean,SO2_max,Temperature_mean,Temperature_max,Wind_speed_mean,Wind_direction_mean,Wind_speed_max,Rel_humidity_mean,Precipitation_sum,Luminosity,elevation,NO2_mean,NO2_max,O3_mean,O3_max
392941,2018-11-01,105.270424,18.920766,Rice,VN,0.508789,49.625000,136.2500,1.246961e-04,0.000125,22.656250,25.578125,0.534180,-0.052765,0.798828,0.825684,0.093750,0.000000,19,0.000034,0.000057,0.009043,0.012944
392942,2018-11-01,105.271322,18.920766,Rice,VN,0.517090,49.625000,136.2500,1.246961e-04,0.000125,22.656250,25.578125,0.534180,-0.052765,0.798828,0.825684,0.093750,0.000000,19,0.000034,0.000057,0.009043,0.012944
392943,2018-11-01,105.272221,18.920766,Rice,VN,0.535156,49.625000,136.2500,1.246961e-04,0.000125,22.656250,25.578125,0.534180,-0.052765,0.798828,0.825684,0.093750,0.000000,19,0.000034,0.000057,0.009043,0.012944
392944,2018-11-01,105.273119,18.920766,Rice,VN,0.557617,49.625000,136.2500,1.246961e-04,0.000125,22.656250,25.578125,0.534180,-0.052765,0.798828,0.825684,0.093750,0.000000,19,0.000034,0.000057,0.009043,0.012944
392945,2018-11-01,105.274017,18.920766,Rice,VN,0.580566,49.625000,136.2500,1.246961e-04,0.000125,22.656250,25.578125,0.534180,-0.052765,0.798828,0.825684,0.093750,0.000000,18,0.000034,0.000057,0.009043,0.012944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62105876,2022-08-01,107.932132,21.498931,Rice,VN,0.442383,7.398438,45.9375,6.758187e-10,0.000347,27.875000,29.984375,1.264648,-0.009193,4.445312,0.868652,0.594238,1.099609,2,NaN,NaN,NaN,NaN
62105877,2022-08-01,107.576399,21.499829,Rice,VN,0.442871,8.937500,470.7500,-5.142217e-05,0.000148,25.828125,27.671875,0.725586,-0.262695,2.496094,0.894043,0.585449,0.000000,-55,NaN,NaN,NaN,NaN
62105878,2022-08-01,107.651858,21.499829,Rice,VN,0.485352,8.937500,470.7500,-6.516201e-05,0.000114,27.015625,29.062500,0.903809,-0.133423,3.193359,0.885254,0.582031,0.000000,79,NaN,NaN,NaN,NaN
62105879,2022-08-01,107.869250,21.499829,Rice,VN,0.501953,7.398438,45.9375,-1.128680e-05,0.000347,27.875000,29.984375,1.264648,-0.009193,4.445312,0.868652,0.594238,0.000000,5,NaN,NaN,NaN,NaN
62105880,2022-08-01,107.877335,21.499829,Rice,VN,0.481934,7.398438,45.9375,-2.437269e-05,0.000347,27.875000,29.984375,1.264648,-0.009193,4.445312,0.868652,0.594238,0.000000,6,NaN,NaN,NaN,NaN

In [49]:
schema = {'RVI_mean': np.float16,
          'PM25_mean': np.float16,
          'PM25_max': np.float16,
          'Temperature_mean': np.float16,
          'Temperature_max': np.float16,
          'Wind_speed_mean': np.float16,
          'Wind_speed_max': np.float16,
          'Wind_direction_mean': np.float16,
          'Rel_humidity_mean': np.float16,
          'Precipitation_sum': np.float16,
          'Luminosity': np.float16,
          'elevation': np.int8}

In [50]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'final_north/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2017-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/final_north\\N18E105_0_0_100m_2018-08-01.csv']

In [51]:
list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv('VN_NORTH_VER2.csv', index=False)

G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-01-01.csv

C:\Users\sonle\AppData\Local\Temp\ipykernel_3760\692221160.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

In [6]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'leaf_north/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2017-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/leaf_north\\N18E105_0_0_100m_2018-08-01.csv']

In [7]:
schema = {'NVDI_mean': np.float16,
          'LAI_mean': np.float16}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv('LEAF_NORTH.csv', index=False)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-10-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-01-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-10-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-07-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-03-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N18E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_0_100m_2022-09-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N19E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-10-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-03-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-05-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-01-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-04-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-05-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-11-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-10-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-09-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-04-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-10-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-03-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-11-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-02-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-04-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N20E106_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-09-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-04-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-09-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-03-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-08-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-05-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-07-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-07-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-02-01.csv

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:234: RuntimeWarning: overflow encountered in cast
  chunks = self._reader.read_low_memory(nrows)

G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E106_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/leaf_north\N21E107_1_1_100m_2022-12-01.csv

C:\Users\sonle\AppData\Local\Temp\ipykernel_13088\106883921.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

In [2]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'sar_south/*.csv'))
paths.sort()

schema = {'VV': np.float16,
          'VH': np.float16,
          'VV/VH': np.float16}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv(os.path.join(dir, 'combined_datasets/SAR_SOUTH.csv'), index=False)

G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E104_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_south\N09E105_1_1_100m_2017-10-01.csv

In [3]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'ghap_south/*.csv'))
paths.sort()

schema = {'GHAP_PM25_mean': np.float16,
          'GHAP_PM25_max': np.float16}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv(os.path.join(dir, 'combined_datasets/GHAP_SOUTH.csv'), index=False)

G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E104_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_south\N09E105_1_1_100m_2017-06-01.csv

In [5]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'ghap_north/*.csv'))
paths.sort()

schema = {'GHAP_PM25_mean': np.float16,
          'GHAP_PM25_max': np.float16}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv(os.path.join(dir, 'combined_datasets/GHAP_NORTH.csv'), index=False)

G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N18E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/ghap_north\N19E105_0_0_100m_2017-06-01.csv

C:\Users\sonle\AppData\Local\Temp\ipykernel_1612\781008152.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

In [4]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'sar_north/*.csv'))
paths.sort()

schema = {'VV': np.float16,
          'VH': np.float16,
          'VV/VH': np.float16}

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
full.to_csv(os.path.join(dir, 'combined_datasets/SAR_NORTH.csv'), index=False)

G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E105_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2017-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N18E106_1_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-01-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-02-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-03-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-04-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-05-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-06-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-07-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-08-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-09-01.csv
G:/My Drive/Work/ADB/SAR/sar_north\N19E105_0_0_100m_2017-10-01.csv

C:\Users\sonle\AppData\Local\Temp\ipykernel_1612\186126782.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full = pd.concat(list_dfs, axis=0).reset_index(drop=True)

In [3]:
df

    Timestamp  NO2_mean  NO2_max   O3_mean    O3_max
0  2018-07-01  0.000008  0.00002  0.005918  0.007911

In [4]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'NO2_O3_IND/*.csv'))
paths.sort()

list_dfs = []

for path in paths:
    print(path)
    df = pd.read_csv(path)
    list_dfs.append(df)
    del df 
    gc.collect()

full = pd.concat(list_dfs, axis=0).reset_index(drop=True)
for col in ['NO2_mean', 'NO2_max', 'O3_mean', 'O3_max']:
    full[col] = full[col].mask(full[col] < 0, 0)

full.to_csv(os.path.join(dir, 'combined_datasets/NO2_O3_IND.csv'), index=False)

G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/NO2_O3_IND\VNM_FIRMS_2022-12-01.csv

In [41]:
import os

paths = glob.glob(os.path.join(dir, 'final_north/*.csv'))
paths.sort()
paths = [p for p in paths if '2017' in p]
paths[:20]
# Specify the path of the file to be deleted
for path in paths:
    # Check if the file exists before attempting to delete it
    if os.path.exists(path):
        os.remove(path)
        print(f"The file {path} has been deleted.")
    else:
        print(f"The file {path} does not exist.")

The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N18E106_1_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_0_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N19E105_1_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_0_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E105_1_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_0_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N20E106_1_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_0_1_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-04-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-05-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-06-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-07-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-08-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-09-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-10-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-11-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_0_100m_2017-12-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_1_100m_2017-01-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_1_100m_2017-02-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_1_100m_2017-03-01.csv has been deleted.
The file G:/My Drive/Work/ADB/SAR/final_north\N21E105_1_1_100m_2017-04-01.csv has been deleted.

# Processing

## Removing category pollutants

In [3]:
schema_in = {'RVI_mean': np.float16,
            'PM25_mean': np.float16,
            'PM25_max': np.float16,
            'NO2_mean': np.float32,
            'NO2_max': np.float32,
            'O3_mean': np.float32,
            'O3_max': np.float32,
            'SO2_mean': np.float32,
            'SO2_max': np.float32,
            'Temperature_mean': np.float16,
            'Temperature_max': np.float16,
            'Wind_speed_mean': np.float16,
            'Wind_speed_max': np.float16,
            'Wind_direction_mean': np.float16,
            'Rel_humidity_mean': np.float16,
            'Precipitation_sum': np.float16,
            'Luminosity': np.float16,
            'elevation': np.int8}


schema_out = {'RVI_mean': np.float16,
            'PM25_mean': np.float16,
            'PM25_max': np.float16,
            'Temperature_mean': np.float16,
            'Temperature_max': np.float16,
            'Wind_speed_mean': np.float16,
            'Wind_speed_max': np.float16,
            'Wind_direction_mean': np.float16,
            'Rel_humidity_mean': np.float16,
            'Precipitation_sum': np.float16,
            'Luminosity': np.float16,
            'elevation': np.int8}

cols_drop = ['NO2_mean', 'NO2_max', 'O3_mean', 'O3_max', 'SO2_mean', 'SO2_max']

In [5]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'outputs/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs\\N09E104_1_1_100m_2019-08-01.csv']

In [8]:
for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema_in)
    df = df.drop(cols_drop, axis=1)
    path_new = path.replace('outputs', 'final_south')
    print(path_new, '\n')
    df.to_csv(path_new, index=False, mode='w+')
    del df 
    gc.collect()

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2019-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2020-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2021-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E104_1_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E104_1_1_100m_2022-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2019-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2020-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2021-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_0_100m_2022-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2019-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2020-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2020-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2020-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs\N09E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_south\N09E105_0_1_100m_2020-04-01.csv


In [9]:
dir = 'G:/My Drive/Work/ADB/SAR/'
paths = glob.glob(os.path.join(dir, 'outputs_north/*.csv'))
paths.sort()
paths[:20]

['G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-08-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-09-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-10-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-11-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2018-12-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-01-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-02-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-03-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-04-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-05-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-06-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-07-01.csv',
 'G:/My Drive/Work/ADB/SAR/outputs_north\\N18E105_0_0_100m_2019-08-01.csv']

In [10]:
for path in paths:
    print(path)
    df = pd.read_csv(path, dtype=schema_in)
    df = df.drop(cols_drop, axis=1)
    path_new = path.replace('outputs_north', 'final_north')
    print(path_new, '\n')
    df.to_csv(path_new, index=False, mode='w+')
    del df 
    gc.collect()

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2019-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2020-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2021-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_0_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_0_100m_2022-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2019-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2019-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2020-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2020-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2021-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2021-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_0_1_100m_2022-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_0_1_100m_2022-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-10-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-10-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-11-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-11-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2018-12-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2018-12-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-01-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-01-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-02-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-02-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-03-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-03-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-04-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-04-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-05-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-05-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-06-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-06-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-07-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-07-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-08-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-08-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-09-01.csv
G:/My Drive/Work/ADB/SAR/final_north\N18E105_1_1_100m_2019-09-01.csv

G:/My Drive/Work/ADB/SAR/outputs_north\N18E105_1_1_100m_2019-10-01.csv

In [1]:
from shapely import Point
import geopandas as gpd
import pandas as pd

df = pd.read_csv('datasets/LEAF_SOUTH.csv', dtype={'Timestamp': 'str',
                                                   'lon': 'float64',
                                                   'lat': 'float64',
                                                   'LAI_mean': 'float32',
                                                   'NVDI_mean': 'float32'})

df = gpd.GeoDataFrame(df[['lat', 'lon']])
df = df.drop_duplicates(subset=['lat', 'lon']).reset_index(drop=True)

In [2]:
df

               lat         lon
0         9.000670  104.865284
1         9.000670  104.903013
2         9.000670  104.951522
3         9.000670  104.953319
4         9.000670  104.954217
...            ...         ...
1616953  11.998348  106.793967
1616954  11.999246  106.780492
1616955  11.999246  106.783187
1616956  11.999246  106.784085
1616957  11.999246  106.790374

[1616958 rows x 2 columns]

In [3]:
df.dtypes

lat    float64
lon    float64
dtype: object

In [4]:
df['geometry'] = gpd.points_from_xy(df['lon'], df['lat'])

In [5]:
import gc
gc.collect()

0

In [6]:
import re
poly = gpd.read_file('gadm41_VNM_1.json')
poly['VARNAME_1'] = poly['VARNAME_1'].apply(lambda x: re.sub(r"(\w)([A-Z])", r"\1 \2",x ))
poly['VARNAME_1'] = poly['VARNAME_1'].str.replace('-', ' - ')
poly = poly[['VARNAME_1', 'geometry']]
poly

            VARNAME_1                                           geometry
0            An Giang  MULTIPOLYGON (((105.54860 10.42950, 105.54950 ...
1   Ba Ria - Vung Tau  MULTIPOLYGON (((107.09010 10.32400, 107.08890 ...
2           Bac Giang  MULTIPOLYGON (((106.28380 21.13230, 106.27340 ...
3             Bac Kan  MULTIPOLYGON (((105.87240 21.85580, 105.86290 ...
4            Bac Lieu  MULTIPOLYGON (((105.42440 9.02130, 105.41640 9...
..                ...                                                ...
58           Tra Vinh  MULTIPOLYGON (((106.41350 9.52920, 106.40880 9...
59        Tuyen Quang  MULTIPOLYGON (((105.51040 21.60470, 105.51410 ...
60          Vinh Long  MULTIPOLYGON (((106.06320 9.94750, 106.06270 9...
61          Vinh Phuc  MULTIPOLYGON (((105.57130 21.16150, 105.53360 ...
62            Yen Bai  MULTIPOLYGON (((104.79460 21.33520, 104.79080 ...

[63 rows x 2 columns]

In [7]:
df = gpd.GeoDataFrame(df)
df = df.set_crs(poly.crs)

In [9]:
df_j = gpd.sjoin(gpd.GeoDataFrame(df), poly)

In [10]:
df_j

,lat,lon,geometry,index_right,VARNAME_1
0,9.000670,104.865284,POINT (104.86528 9.00067),11,Ca Mau
1,9.000670,104.903013,POINT (104.90301 9.00067),11,Ca Mau
2,9.000670,104.951522,POINT (104.95152 9.00067),11,Ca Mau
3,9.000670,104.953319,POINT (104.95332 9.00067),11,Ca Mau
4,9.000670,104.954217,POINT (104.95422 9.00067),11,Ca Mau
...,...,...,...,...,...
1616953,11.998348,106.793967,POINT (106.79397 11.99835),9,Binh Phuoc
1616954,11.999246,106.780492,POINT (106.78049 11.99925),9,Binh Phuoc
1616955,11.999246,106.783187,POINT (106.78319 11.99925),9,Binh Phuoc
1616956,11.999246,106.784085,POINT (106.78409 11.99925),9,Binh Phuoc
1616957,11.999246,106.790374,POINT (106.79037 11.99925),9,Binh Phuoc

In [11]:
df_j = df_j.rename({'VARNAME_1': 'Province'}, axis=1)
pd.DataFrame(df_j[['lat', 'lon', 'Province']]).to_csv('datasets/province_by_coords_SOUTH.csv', index=False)

In [15]:
df_j_n = pd.read_csv('datasets/province_by_coords_NORTH.csv')
df_j_s = pd.read_csv('datasets/province_by_coords_SOUTH.csv')
df_j_s

               lat         lon    Province
0         9.000670  104.865284      Ca Mau
1         9.000670  104.903013      Ca Mau
2         9.000670  104.951522      Ca Mau
3         9.000670  104.953319      Ca Mau
4         9.000670  104.954217      Ca Mau
...            ...         ...         ...
1616827  11.998348  106.793967  Binh Phuoc
1616828  11.999246  106.780492  Binh Phuoc
1616829  11.999246  106.783187  Binh Phuoc
1616830  11.999246  106.784085  Binh Phuoc
1616831  11.999246  106.790374  Binh Phuoc

[1616832 rows x 3 columns]

In [17]:
df_j = pd.concat([df_j_n, df_j_s], axis=0).reset_index(drop=True)
df_j

               lat         lon    Province
0        18.500354  105.329713     Ha Tinh
1        18.500354  105.330611     Ha Tinh
2        18.500354  105.344984     Ha Tinh
3        18.500354  105.365645     Ha Tinh
4        18.500354  105.366544     Ha Tinh
...            ...         ...         ...
2737721  11.998348  106.793967  Binh Phuoc
2737722  11.999246  106.780492  Binh Phuoc
2737723  11.999246  106.783187  Binh Phuoc
2737724  11.999246  106.784085  Binh Phuoc
2737725  11.999246  106.790374  Binh Phuoc

[2737726 rows x 3 columns]

In [18]:
df_j.to_csv('province_by_coords.csv', index=False)

## Processing with Dask

In [1]:
import glob
from tqdm import tqdm_notebook


import numpy as np
import pandas as pd

# from dask.distributed import Client, LocalCluster
# cluster = LocalCluster(n_workers=8, memory_limit="2GB", 
#                        processes=True)
# client = Client(cluster)
# import dask.dataframe as dd

In [5]:
paths = glob.glob(r"G:\My Drive\rice_extra_metrics_south/*")
paths

['G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2021-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2020-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2019-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2018-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_1_0_100m_2017-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2022-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2021-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2020-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2019-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2018-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_1_100m_2017-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2022-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2021-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2020-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2019-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2018-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E105_0_0_100m_2017-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2022-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2021-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2020-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-08-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-03-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-06-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-05-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-04-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-02-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2019-01-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-12-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-07-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-11-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-09-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-10-01_rice.csv',
 'G:\\My Drive\\rice_extra_metrics_south\\N09E104_1_1_100m_2018-08-01_rice.csv',

In [6]:
dfs = []
for p in tqdm_notebook(paths):
    dfs.append(pd.read_csv(p))

df = pd.concat(dfs, axis=0).to_csv(r"D:\Work\ADB\SAR\datasets/VN_SOUTH_extra_metrics.csv", index=False)

C:\Users\sonle\AppData\Local\Temp\ipykernel_15640\78974002.py:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for p in tqdm_notebook(paths):

  0%|          | 0/1152 [00:00<?, ?it/s]

C:\Users\sonle\AppData\Local\Temp\ipykernel_15640\78974002.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(dfs, axis=0).to_csv(r"D:\Work\ADB\SAR\datasets/VN_SOUTH_extra_metrics.csv", index=False)

In [ ]:
# client.close()